In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import re 

In [111]:
words=pd.read_csv('train.csv',delimiter=',')
test=pd.read_csv('test.csv',delimiter=',')

In [112]:
label=words['label']

In [113]:
words.drop(['label'], axis=1)

Unnamed: 0                                             review
0               0  I think they really let the quality of the DVD...
1               1  I'm sorry but this is just awful. I have told ...
2               2  The Japenese sense of pacing, editing and musi...
3               3  In the '60's/'70's, David Jason was renowned f...
4               4  "Hail The Woman" is one of the most moving fil...
...           ...                                                ...
39995       39995  When you come across a gem of a movie like thi...
39996       39996  I don't often go out of my way to write commen...
39997       39997  This is an extremely silly and little seen fil...
39998       39998  Just saw the movie, and the scary thing was, t...
39999       39999  ...though for a film that seems to be trying t...

[40000 rows x 2 columns]

In [114]:
w=np.array(words)
t=np.array(test)
w1=[]
w2=[]
for i in range(40000):
    w1.append(w[i][1])
for i in range(10000):
    w2.append(t[i][1])
w=np.array(w1)
t=np.array(w2)
for i in range(len(w)):
    w[i] = re.sub('<br\s/>',' ',w[i],flags=re.IGNORECASE)
for i in range(len(t)):
    t[i] = re.sub('<br\s/>',' ',t[i],flags=re.IGNORECASE)

In [115]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.stop_words import ENGLISH_STOP_WORDS
from sklearn.feature_extraction.text import TfidfVectorizer

vector = TfidfVectorizer(lowercase=True, stop_words=ENGLISH_STOP_WORDS,
                             analyzer='word',min_df = 0.005)
vector.fit(w)
vector.fit(t)

TfidfVectorizer(min_df=0.005,
                stop_words=frozenset({'a', 'about', 'above', 'across', 'after',
                                      'afterwards', 'again', 'against', 'all',
                                      'almost', 'alone', 'along', 'already',
                                      'also', 'although', 'always', 'am',
                                      'among', 'amongst', 'amoungst', 'amount',
                                      'an', 'and', 'another', 'any', 'anyhow',
                                      'anyone', 'anything', 'anyway',
                                      'anywhere', ...}))

In [116]:
len(vector.vocabulary_)

2955

In [117]:
vector2 = TfidfVectorizer(lowercase=True, stop_words=ENGLISH_STOP_WORDS,
                             analyzer='word',ngram_range=(2, 2),min_df = 0.005)
vector2.fit(w)
vector2.fit(t)

TfidfVectorizer(min_df=0.005, ngram_range=(2, 2),
                stop_words=frozenset({'a', 'about', 'above', 'across', 'after',
                                      'afterwards', 'again', 'against', 'all',
                                      'almost', 'alone', 'along', 'already',
                                      'also', 'although', 'always', 'am',
                                      'among', 'amongst', 'amoungst', 'amount',
                                      'an', 'and', 'another', 'any', 'anyhow',
                                      'anyone', 'anything', 'anyway',
                                      'anywhere', ...}))

In [62]:
len(vector2.vocabulary_)

367

In [118]:
w[0]

"I think they really let the quality of the DVD production get away from them. I rented this DVD from 2 movie stores and the second time I finally got it to play on the 3rd DVD player I tried.  Anyone else have this issue? It's really hard to give the film an un-biased review after going through such a hassle to play it. For one, I've never seen a Finnish horror film before so I was sort of bummed that the movie was done in English. Also since it's never made clear what is wrong with Sarah, she just came off as retarded and therefore I really just hoped someone would shoot her in the face and make all the horrific happenings go away."

Пунктуация ? ! как параметр

In [119]:
ask = np.zeros(len(w))
for i in range (len(ask)):
    ask[i] = w[i].count('?')

In [120]:
ask1 = np.zeros(len(t))
for i in range (len(ask1)):
    ask1[i] = t[i].count('?')

In [121]:
v = np.zeros(len(w))
for i in range (len(v)):
    v[i] = w[i].count('!')

In [122]:
v1 = np.zeros(len(t))
for i in range (len(v1)):
    v1[i] = t[i].count('!')

Количество слов как параметр

In [55]:
#a1 = np.zeros(len(w))
#for i in range (len(a1)):
#    a1[i] = len(w[i].split())

In [69]:
#at1 = np.zeros(len(t))
#for i in range (len(at1)):
#    at1[i] = len(t[i].split())

Количество символов как параметр

In [123]:
a2 = np.zeros(len(w))
for i in range (len(a2)):
    a2[i] = len(w[i])

In [124]:
at2 = np.zeros(len(t))
for i in range (len(at2)):
    at2[i] = len(t[i])

Создание таблицы из параметров-слов, пунктуации и количества слов

In [125]:
x=vector.transform(w)
z=vector.transform(t)

In [126]:
df=pd.DataFrame(x.toarray())
dft=pd.DataFrame(z.toarray())

Слияние двух таблиц

In [74]:
x2 = vector2.transform(w)
z2 = vector2.transform(t)

In [75]:
df2=pd.DataFrame(x2.toarray())
dft2=pd.DataFrame(z2.toarray())

In [76]:
dft2.columns = np.arange(len(list(dft2)))+len(list(dft))

In [77]:
df2.columns = np.arange(len(list(df2)))+len(list(df))

In [78]:
df = df.join(df2)

In [79]:
dft = dft.join(dft2)

Добавление знаков препинания

In [127]:
df['?'] = pd.Series(ask)

In [128]:
dft['?'] = pd.Series(ask1)

In [129]:
df['!'] = pd.Series(v)

In [130]:
dft['!'] = pd.Series(v1)

In [84]:
#df['words'] = pd.Series(a1)

In [85]:
#dft['words'] = pd.Series(at1)

In [131]:
df['lens'] = pd.Series(a2)

In [132]:
dft['lens'] = pd.Series(at2)

Нормировка

In [133]:
cols = df.columns

In [134]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

df = scaler.fit_transform(df)

dft = scaler.transform(dft)

In [135]:
df = pd.DataFrame(df, columns=[cols])
dft = pd.DataFrame(dft, columns=[cols])

Добавление квадратов значений 

In [163]:
dfq = df.copy(deep=True)
dfq = np.square(dfq)
dfq.columns = np.arange(len(list(df)))+len(list(df))
df = df.join(dfq)

In [176]:
dftq = dft.copy(deep=True)
dftq = np.square(dftq)
dftq.columns = np.arange(len(list(dft)))+len(list(dft))
dft = dft.join(dftq)

Запускаем регрессию (потом -- Байеса)

In [138]:
from sklearn.model_selection import train_test_split
df_train, df_test,label_train, label_test = train_test_split(df,label, test_size=0.2, shuffle=True, random_state=123)


In [139]:
# train a logistic regression model on the training set
from sklearn.linear_model import LogisticRegression


# instantiate the model
logreg = LogisticRegression(solver='liblinear', random_state=0)
logreg1 = LogisticRegression(solver='liblinear', random_state=0)

# fit the model
logreg.fit(df, label)
logreg1.fit(df_train, label_train)

LogisticRegression(random_state=0, solver='liblinear')

In [140]:
y_pred_train = logreg.predict(df)
y_pred_test = logreg.predict(dft)

Y_pred_train = logreg1.predict(df_train)
Y_pred_test = logreg1.predict(df_test)

In [141]:
from sklearn.metrics import f1_score

In [142]:
from sklearn.model_selection import KFold
R = df.copy(deep=True)
S = label.copy(deep=True)
kf = KFold(n_splits=5, random_state=132, shuffle=True)
kf.get_n_splits(R)

p=0.
print(kf)

for train_index, test_index in kf.split(R):
    print("TRAIN:", train_index, "TEST:", test_index)
    R_train, R_test = R.iloc[train_index], R.iloc[test_index]
    
    S_train, S_test = S.iloc[train_index], S.iloc[test_index]
    logregK = LogisticRegression(solver='liblinear', random_state=0)
    logregK.fit(R_train, S_train)
    S_pred_test = logregK.predict(R_test)
    p=p+f1_score(S_test, S_pred_test)
    print(f1_score(S_test, S_pred_test))
    logregK=0

KFold(n_splits=5, random_state=132, shuffle=True)
TRAIN: [    0     1     2 ... 39997 39998 39999] TEST: [    3    16    19 ... 39983 39990 39992]
0.8789855964545119
TRAIN: [    1     2     3 ... 39997 39998 39999] TEST: [    0     4     5 ... 39991 39995 39996]
0.87865055387714
TRAIN: [    0     1     3 ... 39997 39998 39999] TEST: [    2     9    13 ... 39986 39987 39993]
0.8765571913929785
TRAIN: [    0     1     2 ... 39995 39996 39999] TEST: [   11    12    15 ... 39994 39997 39998]
0.8764211566979733
TRAIN: [    0     2     3 ... 39996 39997 39998] TEST: [    1     6     7 ... 39984 39989 39999]
0.8918784255107125


In [143]:
R = df.copy(deep=True)
S = label.copy(deep=True)
kf = KFold(n_splits=5, random_state=13, shuffle=True)
kf.get_n_splits(R)
print(kf)

for train_index, test_index in kf.split(R):
    print("TRAIN:", train_index, "TEST:", test_index)
    R_train, R_test = R.iloc[train_index], R.iloc[test_index]
    
    S_train, S_test = S.iloc[train_index], S.iloc[test_index]
    logregK = LogisticRegression(solver='liblinear', random_state=0)
    logregK.fit(R_train, S_train)
    S_pred_test = logregK.predict(R_test)
    p=p+f1_score(S_test, S_pred_test)
    print(f1_score(S_test, S_pred_test))
    logregK=0

KFold(n_splits=5, random_state=13, shuffle=True)
TRAIN: [    0     1     2 ... 39997 39998 39999] TEST: [    5     8    11 ... 39982 39990 39995]
0.8767021539985146
TRAIN: [    0     1     2 ... 39997 39998 39999] TEST: [    6     7    14 ... 39983 39988 39994]
0.8712026110971629
TRAIN: [    0     1     2 ... 39996 39998 39999] TEST: [    3     9    12 ... 39989 39993 39997]
0.8846487424111015
TRAIN: [    0     1     2 ... 39996 39997 39999] TEST: [    4    13    21 ... 39984 39991 39998]
0.8808172531214529
TRAIN: [    3     4     5 ... 39995 39997 39998] TEST: [    0     1     2 ... 39992 39996 39999]
0.8784605834885163


In [144]:
p/10

0.8794324268050066

In [145]:
from sklearn.metrics import f1_score
f1_score(label_test, Y_pred_test)

0.8820398564178734

In [146]:
len(np.where(y_pred_test !=0)[0])

5146

In [147]:
from sklearn.metrics import confusion_matrix
print('New Test metrics')
print(confusion_matrix(label_test, Y_pred_test))

New Test metrics
[[3484  498]
 [ 455 3563]]


In [148]:
from sklearn.metrics import classification_report
print('New Test metrics')
print(classification_report(label_test, Y_pred_test))

New Test metrics
              precision    recall  f1-score   support

           0       0.88      0.87      0.88      3982
           1       0.88      0.89      0.88      4018

    accuracy                           0.88      8000
   macro avg       0.88      0.88      0.88      8000
weighted avg       0.88      0.88      0.88      8000



In [38]:
from sklearn.metrics import confusion_matrix

print('Train metrics')
print(confusion_matrix(label, y_pred_train))

Train metrics
[[18527  1540]
 [ 1303 18630]]


In [39]:
from sklearn.metrics import classification_report

print('Train metrics')
print(classification_report(label, y_pred_train))


Train metrics
              precision    recall  f1-score   support

           0       0.93      0.92      0.93     20067
           1       0.92      0.93      0.93     19933

    accuracy                           0.93     40000
   macro avg       0.93      0.93      0.93     40000
weighted avg       0.93      0.93      0.93     40000



In [40]:
print('New Train metrics')
print(confusion_matrix(label_train, Y_pred_train))

New Train metrics
[[14960  1125]
 [  989 14926]]


In [41]:
print('New Train metrics')
print(classification_report(label_train, Y_pred_train))


New Train metrics
              precision    recall  f1-score   support

           0       0.94      0.93      0.93     16085
           1       0.93      0.94      0.93     15915

    accuracy                           0.93     32000
   macro avg       0.93      0.93      0.93     32000
weighted avg       0.93      0.93      0.93     32000



In [42]:
answer = pd.DataFrame({'ID': np.arange(10000),'Predicted': y_pred_test})

In [43]:
answer

ID  Predicted
0        0          0
1        1          1
2        2          0
3        3          1
4        4          0
...    ...        ...
9995  9995          1
9996  9996          0
9997  9997          1
9998  9998          1
9999  9999          1

[10000 rows x 2 columns]

In [44]:
answer.to_csv('IMDBout19TFit0025.csv',index=False)